In [3]:
#a1(question number 1)
import pandas as pd
import numpy as np

# first of all ...we need to load the data
purchase_data = pd.read_excel("Lab Session Data.xlsx", sheet_name="Purchase data")

# having only relevant data that we need from both matrix a and matrix c
products = purchase_data[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
totpayment = purchase_data[['Payment (Rs)']].values

# for printing the data
print("Matrix A (Products):")
print(products)

print("\nMatrix C (totpayment):")
print(totpayment)

# dimensionality and samples
dimensionality = products.shape[1]
samplecount = products.shape[0]

# this is for rank
matrixrank = np.linalg.matrix_rank(products)

# Compute pseudo-inverse and solve for prices
pseudo_inverse = np.linalg.pinv(products)
product_prices = pseudo_inverse @ totpayment

print("\nVector Space Dimensionality:", dimensionality)
print("Total Vectors in Dataset:", samplecount)
print("Rank of the Product Matrix:", matrixrank)
print("\nEstimated Cost per Product (Candy, Mango, Milk):")
print(product_prices.flatten())


Matrix A (Products):
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C (totpayment):
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]

Vector Space Dimensionality: 3
Total Vectors in Dataset: 10
Rank of the Product Matrix: 3

Estimated Cost per Product (Candy, Mango, Milk):
[ 1. 55. 18.]


In [5]:
#a2(question number 2)
def categorize_customer(payment):
  if payment > 200:
    return 'RICH'
  else:
    return 'POOR'

df['Customer_Category'] = df['Payment (Rs)'].apply(categorize_customer)

display(df[['Customer', 'Payment (Rs)', 'Customer_Category']])

Customer  Payment (Rs) Customer_Category
0      C_1           386              RICH
1      C_2           289              RICH
2      C_3           393              RICH
3      C_4           110              POOR
4      C_5           280              RICH
5      C_6           167              POOR
6      C_7           271              RICH
7      C_8           274              RICH
8      C_9           148              POOR
9     C_10           198              POOR